# To auto build what we need.

env:
  - CABALVER=1.22 GHCVER=7.10.2

before_install:
  - "sudo add-apt-repository -y ppa:hvr/ghc"
  - "sudo apt-get update && sudo apt-get install --no-install-recommends texlive-xetex latex-xcolor texlive-fonts-recommended texlive-latex-extra lmodern texlive-latex-recommended"
  - "sudo apt-get install ttf-wqy-microhei ttf-wqy-zenhei"
  - "sudo apt-get install ghc-$GHCVER cabal-install-$CABALVER"
  - "export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH"
  - "cabal update"
  - "cabal install yesod -j9"
  - "cabal install persistent-postgresql"
  - "cabal install pureMD5"
  - "cabal install SHA"
  - "cabal install cmdargs"


script:
  - cd src
  - xelatex BackEnd.tex
  - xelatex BackEnd.tex
  - xelatex BackEnd.tex
  - cd ..
  - cabal configure
  - cabal build
  - cabal sdist
  - cabal install dist/YrarbilBackend-*.tar.gz

after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    git config --global user.name "travis_auto"
    git config --global user.email "qinka@live.com"
    echo "config done"
    cd ~
    git clone https://qinka:$GITHUB_API_KEY@github.com/XDUDsTeam/YrarbilRelease.git
    echo "clone done"
    cd YrarbilRelease
    ls
    pwd
    export RELPATH=$(pwd)
    ls
    pwd
    cd "$TRAVIS_BUILD_DIR"/src
    ls
    pwd
    cp *.pdf $RELPATH
    echo "copy done"
    cd "$TRAVIS_BUILD_DIR"/dist
    cp *.tar.gz $RELPATH
    cd $RELPATH
    echo $(date) >>ChangeLog.md
    echo "Travis-CI build YrarbilBackend's new push."
    git add .
    git commit -am"$(date)"
    echo "commit done"
    git push origin master
    cd ~
    sudo rm -rf $RELPATH
    cd "$TRAVIS_BUILD_DIR"
  fi
